name: fatl_gemini_chatbot
description: A simple gemini powered chatbot
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  cloud_firestore: ^4.15.4
  dartz: ^0.10.1
  dash_chat_2: ^0.0.20
  firebase_core: ^2.25.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.4.1
  intl: ^0.18.0
  json_annotation: ^4.8.1

dev_dependencies:
  bloc_test: ^9.1.4
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
